### ISSUE TITLE
Using a custom or preinstalled color in the project settings

### ISSUE THREAD

**Issue by creecros** [aljawaid/KBColours#6]
Currently is not possible
![image](https://user-images.githubusercontent.com/26339368/209413318-e8f46b2f-47c1-4e64-b104-885e3416ae69.png)

**Comment by creecros** [comment]
This might not be possible without completely overriding the color model....and i dont want to do that.

**Comment by creecros** [comment]
Oh, NM, the issue is your config template...duh....i can fix that.

**Comment by aljawaid** [comment]
> Oh, NM, the issue is your config template...duh....i can fix that.

big thanks, please do... I will take a break for a bit so we dont mix up code. time for a coffee lol

**Comment by creecros** [comment]
kk, im all done, ill be around tonight if you need me

**Comment by aljawaid** [comment]
Huge thanks. Will get back on it very shortly. If you could kindly check my comment on manually building the modal I'd appreciate it. I commented 9n the fix icon commit.

**Comment by creecros** [comment]
I saw it, are you talking about the remove icon, or the add color button

**Comment by aljawaid** [comment]
Either. They are both modals. I just want to replace the FA icon with inline svg html

**Comment by creecros** [comment]
the remove is not a modal. only the add color button.

you don't like the delete icon? I'd say don't complicate it.

**Comment by aljawaid** [comment]
> the remove is not a modal. only the add color button.
> 
> you don't like the delete icon? I'd say don't complicate it.

remove... yeh I noticed that... is there no confirmation to remove on purpose?

its not that i dont like it.... in this case the delete is fine... but for one or two other plugins I did, the modals icon is the only part i can never change.  I'm trying to keep my plugins away from the old FA version included with kanboard and just add the inline code based on whichever i need.  The PluginManager is a classic example.  To try to solve that issue, I can manually build all modals if i know how to replace the fa with inline svg, instead of using the current css hacks.

**Comment by creecros** [comment]
I'm not currently sold on the idea. svgs are math. math is tedious. as seen in pluginmanager.

https://github.com/kanboard/kanboard/blob/main/app/Helper/ModalHelper.php

you could follow the current helper to customize your own modal. I'm all set though, I don't see the gain. you could also skip the built in modals and link helpers all together and write your own html/php.
